### ISSUE TITLE
[Cadgraf] Demo website

### ISSUE THREAD

**Issue by anish-q** [quintype/malibu#301]
### Task Details
This is a demo website for one of our resellers, Cadgraf. They will be using this site to demo the front end and Platform.

- [x] Need to create a production front end instance for `cadgraf`
- [x] Logo: https://drive.google.com/open?id=1h8X20b3dq-MplSwoWLD7yHcGf6i5wRxa
- [ ] Front-end URL to be https://cadgraf-web.quintype.io
- [ ] Bold instance is already created as `https://cadgraf.quintype.com/`
- [ ] Google Auth to be enabled
- [x] The front-end will be a clone of Prabhat Khabar
- [x] Breaking news to `முக்கிய செய்திகள்`
- [x] Fonts to be used can be found at https://drive.google.com/file/d/1DdZbIVtR7dMQcyngKvOe_EQhSLZpYTWi/view?usp=sharing
- [ ] The site is in Tamil and the content need to come from `https://newspedia-com.quintype.com`
- [x] Story pages `अन्य खबरें` to be `மற்ற செய்திகள்`
- [x] Story pages `संबंधित खबरें` to be `தொடர்பு செய்திகள்`
- [ ] The following fonts has to use for the respective tags:

- TAUN_Elango_Abirami font for Top Heading
- TAUN_Elango_Kamban font for Heading
- TAUN_Elango_Panchali font for Second Heading
- TAUN_Elango_Abirami font for Body.
- Menu titles are in TAUN_Elango_Abirami Fonts

Some sample screen shots attached for your reference.

Front Screen View:
![image](https://user-images.githubusercontent.com/29421484/81340041-ccaf7380-90cc-11ea-91c2-e5dd4d1c6f97.png)

In Story View:
![image](https://user-images.githubusercontent.com/29421484/81340087-e18c0700-90cc-11ea-9228-9b22ecd277e0.png)
![image](https://user-images.githubusercontent.com/29421484/81340102-e5b82480-90cc-11ea-9db4-e0bc566bd006.png)
